### ISSUE TITLE
[Bug Report] 플레이 리스트 명령어 특정언어 오류

### ISSUE THREAD

**Issue by yaj0928** [cotwo0139/JMusicBot-Korean-Translation#1]
**Describe the bug**
플레이 리스트 생성후 곡추가 까지는 가능하지만 특정언어(예:일본어)를 플레이 리스트에 집어 넣을씨 플레이리스트이름임.txt 가 없다면서 오류를 띄웁니다. 하지만 txt내용을 그 영상 링크로 설정할시 작동이 잘됩니다. 특정언어가 안되는것을 해결해주세요.

**Version Info (please complete the following information):**
 - Operating System: [e.g. Windows 64bit]
 - JMusicBot Version: [e.g. 0.2.1]

**Comment by cotwo0139** [comment]
플래이 리스트에는 영상 주소만 삽입해야 합니다. Issue 를 닫습니다

**Comment by yaj0928** [comment]
플레이 리스트에 영상 제목을 입력해도 작동이 됩니다.
